name: Build Project

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
        required: false
      tag:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
        fetch-depth: 0
    - name: Setup Rye
      uses: eifinger/setup-rye@v3
    - name: Install Dependencies
      run: rye sync
    - name: Build
      run: ./build.sh --deploy
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
          name: control-any-sim
          path: dist/ControlAnySim.zip
