name: Build Project

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
        required: false
      tag:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
        fetch-depth: 0
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    - name: Install python
      uses: ./.github/actions/install-python
    - name: Install Dependencies
      run: uv sync
    - name: Build
      run: ./build.sh --deploy
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: control-any-sim
          path: dist/ControlAnySim.zip
