name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  ruff-lint:
    runs-on: 'ubuntu-20.04'

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: install dependencies
        run: uv sync
      - name: lint
        run: uv run ruff check src/
      - name: auto fix
        if: ${{ failure() }}
        run: uv run ruff check --fix src/
      - name: suggest changes
        if: ${{ failure() }}
        uses: parkerbxyz/suggest-changes@v1.0.4

  ruff-format:
    runs-on: 'ubuntu-20.04'

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: install dependencies
        run: uv sync
      - name: format
        run: uv run ruff format --check src/
      - name: auto fix
        if: ${{ failure() }}
        run: uv run ruff format src/
      - name: suggest changes
        if: ${{ failure() }}
        uses: parkerbxyz/suggest-changes@v1.0.4

  mypy:
    runs-on: 'ubuntu-20.04'

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: install dependencies
        run: uv sync
      - name: type check
        run: uv run mypy --disable-error-code "import" src/
