name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  ruff:
    runs-on: 'ubuntu-20.04'

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Rye
        uses: eifinger/setup-rye@v3
      - name: Install Dependencies
        run: rye sync
      - name: lint
        run: rye run ruff check src/
      - name: format
        run: rye run ruff format --check src/
