name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  pylint:
    runs-on: 'ubuntu-20.04'

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Setup Cache
        uses: allanchain/poetry-cache-action@v0.2.2
        with:
          cache-key-prefix: pylint
          ensure-module: pylint
      - name: check
        run: poetry run pylint $(find src/ -name '*.py')
